### ISSUE TITLE
Manifests are listing absolute path over relative path

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#163] opened 2018-06-19 18:12 UTC
Build.Manifest is consistently listing the absolute path on the user's machines to the Manifest rather than relative path from the root of the source tree

**Comment by ilikebits** [comment] 2018-06-19 18:32
What version is this? Can you attach a repro case?

**Comment by ilikebits** [comment] 2018-07-20 04:36
Duplicate of #128.

**Closed by ilikebits** 2018-07-20 04:36 UTC
Labels: type: bug
